export const USER_LOGIN = 'USER_LOGIN'
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED'
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED'
//student
export const STUDENT_FETCH = 'STUDENT_FETCH'
export const STUDENT_FETCH_SUCCEEDED = 'STUDENT_FETCH_SUCCEEDED'
export const STUDENT_FETCH_FAILED = 'STUDENT_FETCH_FAILED'
