export const USER_LOGIN = 'USER_LOGIN'
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED'
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED'
//student
export const STUDENT_FETCH = 'STUDENT_FETCH'
export const STUDENT_FETCH_SUCCEEDED = 'STUDENT_FETCH_SUCCEEDED'
export const STUDENT_FETCH_FAILED = 'STUDENT_FETCH_FAILED'
//get details student
export const DETAIL_STUDENT_FETCH = 'DETAIL_STUDENT_FETCH'
export const DETAIL_STUDENT_FETCH_SUCCEEDED = 'DETAIL_STUDENT_FETCH_SUCCEEDED'
export const DETAIL_STUDENT_FETCH_FAILED = 'DETAIL_STUDENT_FETCH_FAILED'
//update students
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const UPDATE_STUDENT_SUCCEEDED = 'UPDATE_STUDENT_SUCCEEDED'
export const UPDATE_STUDENT_FAILED = 'UPDATE_STUDENT_FAILED'
//delete stdent
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const DELETE_STUDENT_SUCCEEDED = 'DELETE_STUDENT_SUCCEEDED'
export const DELETE_STUDENT_FAILED = 'DELETE_STUDENT_FAILED'
//create stdent
export const CREATE_STUDENT = 'CREATE_STUDENT'
export const CREATE_STUDENT_SUCCEEDED = 'CREATE_STUDENT_SUCCEEDED'
export const CREATE_STUDENT_FAILED = 'CREATE_STUDENT_FAILED'
// FETCH_CLASSES
export const FETCH_CLASSES = 'FETCH_CLASSES'
export const FETCH_CLASSES_SUCCEEDED = 'FETCH_CLASSES_SUCCEEDED'
export const FETCH_CLASSES_FAILED = 'FETCH_CLASSES_FAILED'